apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nupurshahalabs-tls
  namespace: kube-system
spec:
  secretName: nupurshahalabs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nupurshahalabs.work
    - www.nupurshahalabs.work
